import assert from 'node:assert/strict';
import { test } from 'node:test';
import { once } from 'node:events';
import { createListHarness, views } from './task-view-fixtures.mjs';
async function setup(t,rows){const h=createListHarness(rows);const server=h.app.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(resolve=>server.close(resolve)));return {h,get: async query=>{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/tasks?${query}`,{headers:{Authorization:`Bearer ${h.token(['Superadmin'])}`}});return {status:response.status,body:await response.json()};}};}
const bounds='todayStart=2026-10-03T00:00:00Z&todayEnd=2026-10-04T00:00:00Z';
test('list returns full-result counts above the old 200-row cap and maintains counts across pages',async t=>{const {get,h}=await setup(t);const a=await get(`pageSize=25&${bounds}`);const b=await get(`page=2&pageSize=25&${bounds}`);assert.equal(a.status,200);assert.equal(a.body.total,240);assert.equal(a.body.items.length,25);assert.deepEqual(a.body.tabCounts,b.body.tabCounts);assert.notEqual(a.body.items[0].id,b.body.items[0].id);const sql=h.calls.find(call=>call.query.includes('AS [pending_supervisor]')).query;assert(sql.includes('CHARINDEX(@search'));assert(sql.includes('@view'));assert(sql.includes('@uiStatus'));assert(sql.includes('OFFSET @offset'));const ordering=sql.match(/^ORDER BY (.+)$/m)[1].split(',').map(term=>term.trim().split(/\s+/)[0]);assert.equal(new Set(ordering).size,ordering.length,'SQL Server ordering columns must be unique');assert(sql.includes("AND t.AssignedToRoleId IS NOT NULL"));});
test('every view uses server filtering, including paused and historical submitted rows',async t=>{const {get}=await setup(t);for(const view of views){const {status,body}=await get(`view=${view}&pageSize=200&${bounds}`);assert.equal(status,200);assert.equal(body.total,body.tabCounts[view]);if(view!=='all')assert.equal(body.items.length,Math.min(body.total,200));if(view==='in_progress')assert(body.items.every(t=>t.status==='in_progress'&&t.approvalStatus==='None'));if(view==='paused')assert(body.items.every(t=>t.status==='paused'));if(view==='pending_supervisor')assert(body.items.every(t=>t.displayStatus==='pending_supervisor'));}});
test('shared search and approved-only affect both counts and rows; literal search is parameterized',async t=>{const {get,h}=await setup(t);const a=await get(`q=PM-STATE-235&approvedOnly=true&${bounds}`);assert.equal(a.body.total,1);assert.equal(a.body.tabCounts.completed,1);assert.equal(a.body.items[0].maintenanceType,'PM');const b=await get(`q=${encodeURIComponent("'; DROP TABLE pm.PMTasks;--")}&${bounds}`);assert.equal(b.body.total,0);assert(!h.calls.at(-1).query.includes('DROP TABLE'));});
test('invalid view, oversized search, missing or reversed day boundaries and reversed due dates fail before SQL',async t=>{const {get,h}=await setup(t);for(const q of ['view=not-a-view',`q=${'x'.repeat(201)}`,'todayStart=2026-10-03T00:00:00Z','todayStart=2026-10-04T00:00:00Z&todayEnd=2026-10-03T00:00:00Z','dueFrom=2026-10-04&dueTo=2026-10-03']){assert.equal((await get(q)).status,400);}assert.equal(h.calls.length,0);});
test('empty and out-of-range pages keep totals, and independent status/date filters intersect the tab',async t=>{const {get}=await setup(t);const a=await get(`page=99&${bounds}`);assert.equal(a.body.items.length,0);assert.equal(a.body.total,240);const b=await get(`view=upcoming&uiStatus=completed&${bounds}`);assert.equal(b.body.total,0);assert.equal(b.body.tabCounts.all,2);const c=await get(`assigned=unassigned&${bounds}`);assert.equal(c.body.total,0);});
